import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const players = [
  {
    name: "Lionel Messi",
    nationality: "Argentina",
    positions: ["RW", "CAM"],
    overall: 90,
    pace: 80,
    shooting: 88,
    passing: 90,
    dribbling: 94,
    defending: 34,
    physical: 65,
  },
  {
    name: "Kylian Mbappe",
    nationality: "France",
    positions: ["ST", "LW"],
    overall: 91,
    pace: 97,
    shooting: 89,
    passing: 80,
    dribbling: 92,
    defending: 36,
    physical: 76,
  },
  {
    name: "Erling Haaland",
    nationality: "Norway",
    positions: ["ST"],
    overall: 91,
    pace: 89,
    shooting: 93,
    passing: 66,
    dribbling: 80,
    defending: 45,
    physical: 88,
  },
  {
    name: "Kevin De Bruyne",
    nationality: "Belgium",
    positions: ["CAM", "CM"],
    overall: 91,
    pace: 74,
    shooting: 86,
    passing: 93,
    dribbling: 88,
    defending: 64,
    physical: 78,
  },
  {
    name: "Virgil van Dijk",
    nationality: "Netherlands",
    positions: ["CB"],
    overall: 89,
    pace: 78,
    shooting: 60,
    passing: 71,
    dribbling: 72,
    defending: 90,
    physical: 86,
  },
  {
    name: "Alisson Becker",
    nationality: "Brazil",
    positions: ["GK"],
    overall: 89,
    pace: 60,
    shooting: 20,
    passing: 68,
    dribbling: 54,
    defending: 20,
    physical: 80,
  },
  {
    name: "Kyle Walker",
    nationality: "England",
    positions: ["RB", "RWB"],
    overall: 84,
    pace: 93,
    shooting: 54,
    passing: 68,
    dribbling: 74,
    defending: 80,
    physical: 82,
  },
  {
    name: "Achraf Hakimi",
    nationality: "Morocco",
    positions: ["RB", "RWB", "RM"],
    overall: 86,
    pace: 92,
    shooting: 72,
    passing: 76,
    dribbling: 84,
    defending: 72,
    physical: 78,
  },
  {
    name: "Theo Hernandez",
    nationality: "France",
    positions: ["LB", "LWB"],
    overall: 85,
    pace: 90,
    shooting: 73,
    passing: 76,
    dribbling: 83,
    defending: 76,
    physical: 82,
  },
  {
    name: "Rodri",
    nationality: "Spain",
    positions: ["CDM", "CM"],
    overall: 90,
    pace: 62,
    shooting: 76,
    passing: 88,
    dribbling: 82,
    defending: 85,
    physical: 82,
  },
  {
    name: "Jude Bellingham",
    nationality: "England",
    positions: ["CM", "CAM"],
    overall: 88,
    pace: 79,
    shooting: 82,
    passing: 84,
    dribbling: 87,
    defending: 68,
    physical: 82,
  },
  {
    name: "Vinicius Junior",
    nationality: "Brazil",
    positions: ["LW"],
    overall: 89,
    pace: 95,
    shooting: 82,
    passing: 76,
    dribbling: 92,
    defending: 29,
    physical: 66,
  },
  {
    name: "Mohamed Salah",
    nationality: "Egypt",
    positions: ["RW", "ST"],
    overall: 89,
    pace: 88,
    shooting: 87,
    passing: 81,
    dribbling: 89,
    defending: 45,
    physical: 75,
  },
  {
    name: "Ruben Dias",
    nationality: "Portugal",
    positions: ["CB"],
    overall: 88,
    pace: 68,
    shooting: 40,
    passing: 68,
    dribbling: 68,
    defending: 89,
    physical: 84,
  },
  {
    name: "Bukayo Saka",
    nationality: "England",
    positions: ["RW", "RM"],
    overall: 87,
    pace: 86,
    shooting: 79,
    passing: 82,
    dribbling: 87,
    defending: 55,
    physical: 68,
  },
];

async function main() {
  console.log(`Seeding ${players.length} players...`);
  for (const player of players) {
    await prisma.player.upsert({
      where: { id: player.name.toLowerCase().replace(/\s+/g, "-") },
      update: player,
      create: { id: player.name.toLowerCase().replace(/\s+/g, "-"), ...player },
    });
  }
  console.log("Done.");
}

main()
  .catch((err) => {
    console.error(err);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
